#!/bin/bash

cd $OPENSHIFT_REPO_DIR

# server options
LISTEN_OPTS="TCP4-LISTEN:$OPENSHIFT_DIY_PORT,fork,reuseaddr,bind=$OPENSHIFT_DIY_IP"
EXEC_OPTS="EXEC:$OPENSHIFT_REPO_DIR/bashttpd"

# start server
nohup socat $LISTEN_OPTS $EXEC_OPTS 2>&1 > $OPENSHIFT_DIY_DIR/logs/server.log &

echo Started bashttpd server
